export const DOMAIN_AVAILABLE = "DOMAIN_AVAILABLE";
export const DOMAIN_LOADING = "DOMAIN_LOADING";
export const DOMAIN_ERROR = "DOMAIN_ERROR";

export const REGISTER_DOMAIN_FAIL = "REGISTER_DOMAIN_FAIL";
export const DOMAIN_REGISTER_LOADING = "DOMAIN_REGISTER_LOADING";
export const DOMAIN_REGISTER_SUCCESS = "DOMAIN_REGISTER_SUCCESS";

export const DOMAIN_DETAIL_SUCCESS = "DOMAIN_DETAIL_SUCCESS";
export const DOMAIN_DETAIL_ISLOADING = "DOMAIN_DETAIL_ISLOADING ";
export const DOMAIN_DETAIL_FAIL = "DOMAIN_DETAIL_FAIL ";
